---
#version: "3.9"

services:
  jupyter-lab:
    image: jupyter/pyspark-notebook
    ports: [8888:8888, 8050:8050]
    volumes: [./home:/home/test_user]

  nginx-proxy:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
    ports: [$PROXY_PORT:3000]
    build:
      network: ${NETWORK:-default}
      context: nginx-proxy
    environment:
      APP_PORT: "8888"
      APP_HOST: "jupyter-lab"
      AUTH0_TENANT_DOMAIN: ${AUTH0_TENANT_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      LOGOUT_URL: ${LOGOUT_URL}
      USERNAME: ${USERNAME}
      REDIRECT_DOMAIN: ${REDIRECT_DOMAIN}
